version: "3"

services:
  university:
    build:
      context: .
    platform: linux/amd64
    ports:
      - 8000:8000
    volumes:
      - .:/app:cached
    command: npm start

  cli:
    build:
      context: .
    platform: linux/amd64
    volumes:
      - .:/app:cached
